image: python:3.7-alpine

before_script:
   - apk add gcc musl-dev python3-dev libffi-dev openssl-dev
   - pip install twine
   - pip install sphinx
   - python setup.py sdist

deploy:
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  script:
    - twine upload dist/*
  only:
    - master

build_other_docs:
  stage: deploy
  script:
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.aimms.com/aimms/customer-support/aimms-how-to/trigger/pipeline
  only:
    - master