image: python:3.7-alpine

before_script:
   - apk add --no-cache openssl-dev libffi-dev
   - pip install twine
   - pip install re
   - pip install pygments
   - pip install sphinx
   - python setup.py sdist

deploy:
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  script:
    - twine upload dist/*
  only:
    - master