image: python:3.8-alpine

before_script:
   - pip install twine
   - python setup.py sdist

deploy:
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  script:
    - twine upload dist/*
  only:
    - master